name: Build GameServerHook

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Add MSVC (VS Build Tools)
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x86   # Win32 必须用 x86

    - name: Build DLL
      run: msbuild GameServerHook.sln /p:Configuration=Release /p:Platform=Win32 /m

    - name: Upload DLL
      uses: actions/upload-artifact@v4
      with:
        name: GameServerHook
        path: |
          Release\GameServerHook.dll
